### ISSUE TITLE
As a user, I can access a dashboard showing status for all my active tasks

### ISSUE THREAD

**Issue by ValentinViennot** [thepinkowl/gauges#1]
┆Attachments: <a href="https://trello-attachments.s3.amazonaws.com/5eb1bfcdbbea1f4bcd3d771d/5eb1cc29b53359730c869f78/b42b169ceed938e40ffea63af53d3578/image.png">image.png</a>

**Comment by ValentinViennot** [comment]
@rogerxaic I've added the screens for the dashboard!

**Comment by ValentinViennot** [comment]
Could be please change it so that the animation does not loop on the welcome page?

**Comment by rogerxaic** [comment]
`loop: false`, and it appears to work.
