### ISSUE TITLE
Bug: When I create a task and mark it as done "today" it shows "done X hours ago"

### ISSUE THREAD

**Issue by ValentinViennot** [thepinkowl/gauges#9]
It should display "a few seconds ago" instead.

![image](https://user-images.githubusercontent.com/18735898/80819917-3368f480-8bd6-11ea-86e9-f0237d3b797e.png)

![image](https://user-images.githubusercontent.com/18735898/80819930-3bc12f80-8bd6-11ea-9c1a-70d5e37c6e44.png)

**Comment by ValentinViennot** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When I create a task and mark it as done "today" it shows "done X hours ago"](https://trello.com/c/auuhUDZf/16-when-i-create-a-task-and-mark-it-as-done-today-it-shows-done-x-hours-ago)

**Comment by rogerxaic** [comment]
This is working as expected
